### ISSUE TITLE
No fan control

### ISSUE THREAD

**Issue by MrBeefDev** [christian-ek/se.calima.pax#3]
Homey can now find my fan and read the data such as temperature, light levels etc, but I can't seem to switch the fan off, or control the fan speed in any way.

**Comment by christian-ek** [comment]
There is no way to turn off the fan except for turning down the speed. If turning down the trickle speed isn't working for you there might be another issue. Homey is having big issues with bluetooth so might be connection issues.

**Comment by MrBeefDev** [comment]
Ahh , it must be a connection issue then, changing the trickle speed has no effect either. But this is the furthest I've managed to get so hopefully that's a positive sign regarding their Bluetooth issues. Thanks for the quick response, and amazing stuff from your side!

**Comment by MrBeefDev** [comment]
Cheers
